name: Check Python Package

on:
  push:
  pull_request:
    branches: [ master ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:

  check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install tox
    - name: Run Tests
      run: tox -e py3

  code-ql:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        queries: security-and-quality
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  doc8-lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Run reStructuredText Linter
      uses: deep-entertainment/doc8-action@v5
      with:
        scanPaths: ${{ github.workspace }}

  flake8-lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Run flake8 Linter
      run: |
        pip install -e . flake8
        flake8 --count --show-source --statistics src test
